### ISSUE TITLE
release: pack requirements for next version

### ISSUE THREAD

**Issue by maxux** [threefoldtech/quantum-storage#15]
Next QSFS version will contains:
- `0-db` v2.0.0-rc3
- `0-db-fs` v0.1.7
- `0-stor` v0.3.0-rc.1
- Configurations

Theses build needs to be staticly compiled since every project attached now support that (previously, we had to ship some shared libraries).

This needs to build on latest V release.

**Comment by sasha-astiadi** [comment]
update the versioning @maxux

**Comment by maxux** [comment]
Updated next QSFS version will contains:

- 0-db v2.0.0-rc5 (static)
- 0-db-fs v0.1.7
- 0-stor v0.3.0-rc.3
