### ISSUE TITLE
QSFS unclear documentation

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/quantum-storage#23]
Unclear documentation on how to interact with QSFS, how to check status, healthy, size, policy, etc.

Looked into the following sites:

https://library.threefold.me/info/manual/#/technology/threefold__qsfs
https://github.com/threefoldtech/quantum-storage

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/62

**Comment by robvanmieghem** [comment]
https://github.com/threefoldtech/quantum-storage/blob/master/docs/operations.md
