### ISSUE TITLE
Missing documentation regarding qsfs deployment in "full VM"

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/quantum-storage#35]
The manuals document how to deploy a QSFS instance, but this always talks about (well not explicitly) using the qsfs as rootfs in a container. This works fine since zos does all the plumbing, so in the end you are left with a container on top of the qsfs.

In the usecase of "full VMs" however, you already have a root disk. Qsfs here is mounted just like other disks. However unlike a regular disk (which uses virtio-blk as transport), qsfs does not automatically appear in the VM (even though a mountpoint is actually specified in e.g. terraform). I'm not sure if cloud init could be used to auto mount it, but for now it requires a manual mount. Since the Virtio-fs transport is used to pass the qsfs to the guest, it needs to be mounted as `mount -t virtiofs <fs_tag> <mountpoint>`. the `<fs_tag>` part is where the main issue is, as it is actually not clear how this is generated (seems to be twinid+deploymentid+diskname, though I'm not sure). This is also not communicated back to the user it seems (at least not in terraform?).

**Comment by xmonader** [comment]
as a result of the research we found this bug in zos https://github.com/threefoldtech/zos/commit/964b654de6807a73e125356b42fcf29d3c9f4cbc yesterday

**Comment by sameh-farouk** [comment]
**Update:**
- Added info about the full flow of deploying QSFS on fullVMs to the manual (PR waiting for review).
- the fix mentioned by @xmonader was verified on devnet. now disk name only used instead of twinid+deploymentid+diskname.
