### ISSUE TITLE
Improvements for recovering on a different front end machine

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/quantum-storage#38]
As part of a recent push to document manual deployment of QSFS (rather than as a grid primitive), I have been doing some tests around recovering the QSFS setup on a different front end machine than the original set up.

The hard requirements to recover can be summarized as:

1. The zstor config file
2. The indexes for the front end zdb, including the namespace files (zdbfs-data and zdbfs-metadata namespaces)

In theory, this is enough for the system to start retrieving zdb data blocks for the provided indexes and making the contained files available over zdbfs. That is with the caveat of course that only finalized data blocks are stored in zstor so we are accepting the loss of data in one unfinalized block, if it exists.

In practice, there is another requirement:

4. The index and data file for the unfinalized zdb datablock (the last one to be generated, which has not become immutable yet)

Without this, at least in my tests, zdb does not function properly and thus zdbfs cannot serve any files, not even those in the completed data blocks.

Finally, when using `zdbfs -o autons` to set up QSFS originally, we add the following requirement at recovery time:

5. Provide a `zdbfs-temp` namespace in zdb that uses the same password as the default for `autons`

The issue here is that `autons` tries first to create the `zdbfs-meta` namespace, and if it fails it does not try any of the others (it just skips to trying to serve the filesystem). This is the least of our worries, because we can easily recreate this namespace by issuing the proper commands, but it is annoying and the UX can be improved.

## The status quo

If we check [`zdb-hook.sh`](https://github.com/threefoldtech/quantum-storage/blob/master/lib/zdb-hook.sh), we can see that we are most of the way to having everything we need to recover. Namely, the namespace files and indexes for finalized blocks are stored.

What's missing really is the unfinalized index and data file for each of the non temp namespaces.

## The workaround

I've tested a bit with patching the hook script so that there's always *some* form of the unfinalized data block and its index stored. This works to prove the concept, but it's clearly a hack. If we are trying to back up empty data blocks just to keep zdb happy when it's time to recover, then I think there must be a better way.

## Proposed changes

I want to thus propose two changes in the supporting tools for QSFS. Maybe there's a better way overall—happy to hear it if there is.

1. Give zdb the ability to detect and recover automatically if it starts up and has only a set of finalized indexes. That is, it can automatically open a new index and data file and continue on normally, as it it had just filled or rotated a data block
2. Make zdbfs `autons` able to create the `zdbfs-temp` namespace whenever it is missing, even if the other two namespaces already exist

This way, we can simply restore the indexes and namespace files for `zdbfs-meta` and `zdbfs-data`, then start up `zdb` and `zdbfs` and pick up where we left off. Any data in the unfinalized block is lost forever, which is fine, that's what `rotate` is for.

**Comment by maxux** [comment]
Hey,

Thanks for your input ! Here is what -I suspect- happens in your situation:
- When zdbfs writes changes/data, it does some `SET` to update inode information (which contains list of blocks, list of files, etc.) and the blocks itself. If an inode `SET` fit at the end of an index/datafile and all/some blocks are saved in the next index/datafiles, for `zdb` this is all fine but for zdbfs, you'll hit some error, some blocks will be missing.

About your proposed changes:
1. It's not possible for zdb to know if last index/data files are missing, there is no information about the state or expected files present. But zdb should not complains even if theses files are missing. Could you send me a set of index/data files in which this happen ?
2. This is quite easy to implement. But `autons` is a flag made to make life easier when it comes to test or play with `zdbfs`, namespace management is supposed to be managed by the __something__ which manage all the   system.

Here are some other solution I suggest:
- When you are stopping zdbfs instance, zdbfs could send `NSJUMP` command which would force namespace to finalize a index/datafile, this in addition would trigger the `zstor` upload process and you should have a complete set uploaded at that moment.
- In order to make this `NSJUMP` more automated, you can start `zdb` with `--rotate X` where `X` is seconds after which index and data are forced to jump as well, this would ensure that namespace are pushed to the backend after `X seconds` even if `datasize` is not reached.

**Comment by scottyeager** [comment]
Hi @maxux and thanks for taking a look.

I should clarify a couple things first:

1. We are assuming that the frontend machine can go offline unexpectedly, thus we don't necessarily have a chance to influence how zdbfs is shutting down
2. Indeed `--rotate` is in use already in my tests. So the question becomes how can we recover all data since the last rotation in event of unexpected failure

> This is quite easy to implement, but autons is a flag made to make life easier when it comes to test or play with zdbfs, namespace management is supposed to be managed by the something which manage all the system.

That's fair enough. I think I found an acceptable solution in the meantime, which is to just backup the namespace file for `zdbfs-temp` and restore only that.

> It's not possible for zdb to know if last index/data files are missing, there is no information about the state or expected files present. But zdb should not complains even if theses files are missing. Could you send me a set of index/data files in which this happen ?

So here I assumed that zdb would somehow store the fact that a data block has become immutable in an explicit way. But perhaps that's not needed under normal operation because the highest index data block is always the open/mutable one.

I can demonstrate the issue with a short reproducible demo. We'll leave zstor out entirely and just simulate its operation, to keep things simple.

## Repro steps

First download the latest binaries and start them up:

```
wget -O zdbfs https://github.com/threefoldtech/0-db-fs/releases/download/v0.1.10/zdbfs-0.1.10-amd64-linux-static
wget -O zdb https://github.com/threefoldtech/0-db/releases/download/v2.0.8/zdb-2.0.8-linux-amd64-static
chmod +x zdb*

mkdir ./data
mkdir ./mnt

# Short rotate time only for demo purposes
./zdb --index ./data/index --data ./data/data --logfile ./zdb.log --background --rotate 1
./zdbfs ./mnt -o background -o autons
```

We actually don't need to write any data into zdbfs. Just its normal startup stuff will cause some data to be written to both data and metadata namespaces. Let's check what happened:

```
$ tree -h data
[  18]  data
├── [  92]  data
│   ├── [   4]  default
│   │   └── [  28]  d0
│   ├── [   8]  zdbfs-data
│   │   ├── [  78]  d0
│   │   └── [  28]  d1
│   ├── [   8]  zdbfs-meta
│   │   ├── [1.3K]  d0
│   │   └── [  28]  d1
│   └── [   8]  zdbfs-temp
│       ├── [  78]  d0
│       └── [  28]  d1
└── [  92]  index
    ├── [  30]  default
    │   ├── [  29]  i0
    │   └── [  22]  zdb-namespace
    ├── [  34]  zdbfs-data
    │   ├── [  71]  i0
    │   ├── [  29]  i1
    │   └── [  25]  zdb-namespace
    ├── [  34]  zdbfs-meta
    │   ├── [ 323]  i0
    │   ├── [  29]  i1
    │   └── [  25]  zdb-namespace
    └── [  34]  zdbfs-temp
        ├── [  71]  i0
        ├── [  29]  i1
        └── [  30]  zdb-namespace
```

We can see that `zdbfs-data` and `zdbfs-meta` have both rotated their data blocks and have a fresh, empty `d1` along with the corresponding indexes `i1`. There's also temp data, which I assume to be disposable.

Let's simulate recovery now. Based on the hook script in this repo, only `d0`, `i0`, and the name space files will have been backed up. Temp data is not backed up at all, but we'll copy over the namespace file to simulate restoring the namespace somehow.

```
pkill zdbfs
pkill zdb

cp -r data data-recovery
rm data-recovery/data/zdbfs-temp/*
rm data-recovery/index/zdbfs-temp/i*
rm data-recovery/data/zdbfs-meta/d1
rm data-recovery/data/zdbfs-data/d1
rm data-recovery/index/zdbfs-meta/i1
rm data-recovery/index/zdbfs-data/i1
```

Now we can start zdb and indeed it won't complain, but zdbfs will give an error:

```
./zdb --index ./data-recovery/index --data ./data-recovery/data --logfile ./zdb-recovery.log --background --rotate 1
./zdbfs-0.1.10-amd64-linux-static /mnt -o background -o autons

```console
[+] initializing zdbfs v0.1.10
[+] blocks cache size: 4096 KB
[+] zdb: auto creating namespace
[-] zdb: nsnew: zdbfs-meta: This namespace is not available
[-] zdb: could not auto create metadata namespace: zdbfs-meta
[-] zdb: set initial: redis error reply: undefined
[-] initializer: initializing namespace magic <ZDBFST> failed

[-] initializer: initial id mismatch (expected 0x00): 0x1
```

Zdb has not written anything at all to the new log file. We can also see that zdb has not created new data files or indexes:

```
tree -h data-recovery/
[  18]  data-recovery/
├── [  92]  data
│   ├── [   4]  default
│   │   └── [  28]  d0
│   ├── [   4]  zdbfs-data
│   │   └── [  78]  d0
│   ├── [   4]  zdbfs-meta
│   │   └── [1.3K]  d0
│   └── [   4]  zdbfs-temp
│       └── [  28]  d0
└── [  92]  index
    ├── [  30]  default
    │   ├── [  29]  i0
    │   └── [  22]  zdb-namespace
    ├── [  30]  zdbfs-data
    │   ├── [  71]  i0
    │   └── [  25]  zdb-namespace
    ├── [  30]  zdbfs-meta
    │   ├── [ 323]  i0
    │   └── [  25]  zdb-namespace
    └── [  30]  zdbfs-temp
        ├── [  29]  i0
        └── [  30]  zdb-namespace
```

When actually using zstor, we'd like to be able to just restore all the indexes, then start up zdb and let the hook take care of restoring the data files as needed.

So assuming I am understanding correctly, my revised suggestion for zdb would be:

1. Set a flag in the index files when a data block has become immutable, either due to being filled or due to rotation
2. On start, if the last index file (highest number) is marked immutable then create a new empty index and data file

**Comment by scottyeager** [comment]
So I figured out eventually that the operation I was asking for is already there in `NSJUMP` (thanks for pointing that out, @maxux). I tried using this in the way I thought was needed, but it didn't work. I still had the same error.

At that point I had narrowed it down. The only thing that was different between my original data folder and the recovery data folder was `zdbfs-temp`. I was assuming based on what I read in [`zdb-hook.sh`](https://github.com/threefoldtech/quantum-storage/blob/master/lib/zdb-hook.sh) that this data is disposable, since it's not backed up to zstor, but I guess that's not actually the case.

Now I also see and understand that it doesn't matter whether the empty data blocks are restored. Zdb will happily use the highest numbered block, as long as it's smaller than `--datasize`, and that makes sense if indeed rotated data blocks are not any different than open ones.

Assuming I have everything correct now, all that's needed is to adjust the hook script to store the temp data. I'll do some further tests to make sure it all works how I expect.

**Comment by maxux** [comment]
I can't remember without reading code how was temp namespace exactly used for but I remember I use it as a namespace that we can reset, it's used as an area where the always append is not a problem, as soon as we don't need data from that namespace we reset it, dropping history etc. It's a workaround to have a local cache writable without suffering from all the history and growing size issue.

**Comment by scottyeager** [comment]
So I have solved all issues around recovery finally, with the following notes:

* I was in some cases trying to test too fast and the zdbfs cache for metadata was not getting flushed to disk and thus not getting backed up to zstor
* Problems with the `zdbfs-temp` namespace are solved by https://github.com/threefoldtech/0-db-fs/commit/ab33ba3c41605d2b7bc0d65d1d2645ed1cbe61b2 (this actually implements the behavior I was asking for above)

Therefore no code changes are needed or desired, to the hook script or otherwise. Thanks @maxux.
