### ISSUE TITLE
Quantum safe filesystem v0.4-0.4.x

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/quantum-storage#4]
## redundant ETCD backend

- [x] use etcd redundant backend

## time based upload

- [x] timebased upload (using zero-stor) @maxux 
- [x] ALL storage containers (also metadata)
- [x] support index dirty detection in zdb @maxux
- [x] upload changed (dirty) index, use ETCD to keep required metadata @LeeSmet 

## backend ZDB

- multi level ZDB stor so we can support millions of backend files
  - more information needed

## restore part

- [x] Make sure we can easily restore

- [x]  retrieve from etcd as metadata stor, so people can easily recreate from where they were with max e.g. 15 min delay @LeeSmet 

## Logging

- [x] logfile to show which files are deleted, modified, added with timestamp, with size @maxux
- [x]  logfile for zero-stor: which shows which files uploaded, timestamp, size, destinations, ... @LeeSmet 

## monitoring / repair tool

- [x] Need rust based monitoring/repair tool (small) @LeeSmet  https://github.com/threefoldtech/quantum-storage/issues/5

- [x]  check health of backends 
- [x]  if missing ZDB's repair on other location 
  
#### Requirements Repair Tool

  - need to make sure we cannot have silent data loss
  - when out of capacity ask for extra ZDB to evdc controller

**Comment by maxux** [comment]
Update status:
- 0-db-fs support locked namespace: https://github.com/threefoldtech/0-db-fs/issues/8
- 0-db supports external hook initialization status: https://github.com/threefoldtech/0-db/issues/100
- 0-db supports data/index path via NSINFO: https://github.com/threefoldtech/0-db/issues/102
- 0-db supports list of running hooks monitoring: https://github.com/threefoldtech/0-db/issues/104

Monitoring tool can now query 0-db to get instance and real-time information needed for some part.

Coming:
- 0-db support of time based data rotation: https://github.com/threefoldtech/0-db/issues/101
- 0-db support of index dirty changes tracking: https://github.com/threefoldtech/0-db/issues/103

**Comment by LeeSmet** [comment]
All required features are done in zstor, except for the notification of failed uploads. Implementation of that will depend on the monitoring tool

**Comment by weynandkuijpers** [comment]
Can we have a new release done / ready for testing.  Want to create a new video about this and share with the larger community.

**Comment by maxux** [comment]
I'm on it, releasing new version and populating everything together.
I'm writing auto-release script to make next release easier to publish.

**Comment by maxux** [comment]
Will implement zdbfs logfile tomorrow (but this is not **needed**)

**Comment by maxux** [comment]
Version 0.0.4 released: https://github.com/threefoldtech/quantum-storage/releases/tag/v0.0.4
This version include latest zstor and latest zdb/hook.

**Warning**: default configuration provided for backend is not valid anymore, but using a custom evdc config works.

**Note**: logfile is not supported for zdbfs, this require more work but this doesn't change workload and kind of log can be generated using debug binary if needed.

**Comment by weynandkuijpers** [comment]
Will verify today.

**Comment by maxux** [comment]
0-db-fs logfile implemented via https://github.com/threefoldtech/0-db-fs/pull/12
Will test and release soon.

**Comment by weynandkuijpers** [comment]
Issue verified and closed.

**Comment by maxux** [comment]
I'm going to release next bootstrap including zdb 2.0 which does not have files limitation.

**Comment by weynandkuijpers** [comment]
Can I have a look at the release?   The latest published release  is still 0.4.... :-)

**Comment by maxux** [comment]
Will take a look with @LeeSmet to release latest version of the bootstrap
